### ISSUE TITLE
みずしまレビュー１

### ISSUE THREAD

**Issue by mizushima1226** [dende-h/react-project#1]
1. 配列のスプレッド構文の活用について

https://github.com/dende-h/react-project/blob/928b440d559be7e94188e5037d9cb6094bf2f388/src/App.jsx#L155-L168

`deleteZoneId `/ `columnsId `と取り方ですが、
```
[deleteZoneId, ...columnsId] = todoList.dropZoneOrder;
```
みたいな感じでスプレッド構文使ってあげるとスッキリかけます👍
そもそも１つの配列に`deleteZoneId `/ `columnsId `の２つをまとめない方がいい、というような考え方もありますが、
実案件でもこのような状況が生まれることあるのでtipsとして覚えとくといいかもです💡

2. inputMessFlagの命名について

いくつかpointあります💡
１つは名称の省略で、MessageをMessに省略するのを良しとしない考えがあります
練習でのtodoアプリでの規模では汲み取りやすいですが、独自の省略を他の人が理解できない可能性があるので注意です〜

xxxFlagという命名ですが、Flagなのでbooleanであることは伝わりますが、inputが「入力済み」のメッセージなのか、
「不正なinputが入力された」のかなど、xxxFlagとすると、どちらの意味でも取れる命名になりやすいので
今回の場合は、`isInvalidInputTodo`のようにすると「不正なTodoの入力である」の意図が伝わりやすいかなぁと思いましたっ
（あくまでも一例です〜）

**Comment by dende-h** [comment]
指摘の箇所修正しました！
スプレッド構文で書くとほんとにスッキリですね！
